feat: wallet UI
bitcointranscripts/transcription-review-front-end pull request #144
Opened 2023-07-29 12:29 UTC by BalogunofAfrica

Fixes https://github.com/bitcointranscripts/transcription-review-front-end/issues/141

2023-07-30 02:43 UTC, Extheoisah requested changes

2023-07-30 02:43 UTC, Extheoisah commented on src/pages/wallet/index.tsx
> +              <Text fontWeight={"bold"}>ID:</Text>
we don't want to show the wallet id. the user doesn't need this info

2023-07-30 02:43 UTC, Extheoisah commented on src/pages/wallet/index.tsx
> +              <Button
We should disable this button if the balance is zero (0)

2023-07-30 02:51 UTC, Extheoisah commented
We should also sort the transactions date from newest to oldest

2023-07-30 02:55 UTC, Extheoisah commented on src/components/alerts/WalletAlert.tsx
> +        onSuccess: (response) => {
on success, we should close the withdraw dialog

2023-07-30 06:02 UTC, BalogunofAfrica commented
@Extheoisah I believe the sorting should be done from the query point, i.e the backend

2023-07-30 09:21 UTC, Extheoisah commented on src/pages/wallet/index.tsx
> +            <Text fontWeight={"medium"}>{walletData?.balance ?? 0}</Text>
lets show the currency denomination e.g. 21,000 SAT

2023-07-31 07:50 UTC, Extheoisah approved these changes

2023-07-31 07:51 UTC, merged