feat: custom directory and selecting of an existing directory
bitcointranscripts/transcription-review-front-end pull request #145
Opened 2023-07-29 13:27 UTC by 0tuedon

2023-07-29 13:39 UTC, 0tuedon commented
This PR references #131  and commit history issues have been fixed

2023-08-12 15:14 UTC, 0tuedon commented
@Extheoisah  @Emmanuel-Develops , An update has been made to fit PR #168  for the directories

2023-08-12 15:27 UTC, 0tuedon commented
https://github.com/bitcointranscripts/transcription-review-front-end/assets/90271995/3703ab7d-a4db-4e5f-a0b6-68110819c60d

2023-09-07 12:15 UTC, Emmanuel-Develops requested changes
A couple of logic that needs to be implemented
- [ ]  selecting a nested directory should update the path, e.g advancing-bitcoin/2021 and not only 2021
- [ ] users can save their selected directories on the save button
- [ ] if user has selected an arbitrary/custom directory, append that directory to the list
- [ ] when navigating with the back button, go back one level up the directory

2023-09-08 22:52 UTC, 0tuedon commented
> A couple of logic that needs to be implemented
> 
> * [ ]   selecting a nested directory should update the path, e.g advancing-bitcoin/2021 and not only 2021
> * [ ]  users can save their selected directories on the save button
> * [ ]  if user has selected an arbitrary/custom directory, append that directory to the list
> * [ ]  when navigating with the back button, go back one level up the directory

Okay, on this

2023-09-18 19:26 UTC, 0tuedon commented
Hey @Emmanuel-Develops, i have made some updates to this PR, you could go through it and LMKWYT.

2023-09-19 11:33 UTC, Emmanuel-Develops commented
> Hey @Emmanuel-Develops, i have made some updates to this PR, you could go through it and LMKWYT.

Looks Good, Nice!

2023-09-19 11:37 UTC, Emmanuel-Develops reviewed
One last thing, can you add filtering to the list

This is good so that when user want to create an arbitrary directory they can see a list of similar ones, incase it already exists. 
Or just generally quickly find a specific directory.

2023-09-19 18:18 UTC, Emmanuel-Develops commented
> One last thing, can you add filtering to the list. We discussed it in the last meeting (I forgot to include it in the checklist above)
> 
> This is good so that when user want to create an arbitrary directory they can see a list of similar ones, incase it already exists. Or just generally quickly find a specific directory.

Let's make this a separate PR, as an additional feature on the nested directories

2023-09-19 18:22 UTC, Emmanuel-Develops commented on src/types/api/dir.ts
> +export type Links = {
and this?

2023-09-19 19:33 UTC, 0tuedon commented on src/types/api/dir.ts
> +export type DirectoryRes = {
nope

2023-09-19 19:33 UTC, 0tuedon commented on src/types/api/dir.ts
> +export type Links = {
not in use

2023-09-21 19:02 UTC, 0tuedon commented
@Emmanuel-Develops  could you check this out again?

2023-09-21 19:13 UTC, Emmanuel-Develops commented
> @Emmanuel-Develops could you check this out again?

alright, checking it out!

2023-09-22 10:06 UTC, Emmanuel-Develops approved these changes
Looks good!
Other changes will be in a separate pr

2023-09-22 10:09 UTC, merged