Admin page (Table Status, Search by username)
bitcointranscripts/transcription-review-front-end pull request #287
Opened 2024-05-02 09:30 UTC by 0tuedon

PR Checklist

- [x]  Data Display in a Table: 
- [x]  Filtering Options 
- [x] Default View: 

**How to Test**
To test this pr make sure you are an admin and navigate to `reviews/all` or use the sidebar navigation.

2024-05-06 15:01 UTC, Extheoisah requested changes

2024-05-06 15:01 UTC, Extheoisah commented on src/pages/reviews/all.tsx
> +const Transactions = () => {
if this component is the same as the `Transactions` component, we should make it dynamic to avoid duplicate code

2024-05-06 15:44 UTC, 0tuedon commented on src/config/ui-config.ts
> +  ALL_REVIEWS: "reviews/all?status=active",
One of the the requirement for issue #282  is to have a default view 
> | Default View: Upon accessing the page, the table should by default display 'Active' reviews.

2024-05-06 15:44 UTC, 0tuedon commented on src/components/tables/TableItems.tsx
> +export const AdminGroupedLinks = ({ data }: { data: AdminReview }) => {
Okay

2024-05-07 13:28 UTC, Extheoisah commented
When I'm on the review page, the Review text doesn't have a background color to show that I'm on that route like we have for the Transactions page. We should use the same background color when the review page is in focus
![image](https://github.com/bitcointranscripts/transcription-review-front-end/assets/60826700/0c61bbe6-41ac-4732-8d09-d3178640f957)

2024-05-07 15:00 UTC, 0tuedon commented
> When I'm on the review page, the Review text doesn't have a background color to show that I'm on that route like we have for the Transactions page. We should use the same background color when the review page is in focus ![image](https://private-user-images.githubusercontent.com/60826700/328540474-0c61bbe6-41ac-4732-8d09-d3178640f957.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwOTExNDMsIm5iZiI6MTcxNTA5MDg0MywicGF0aCI6Ii82MDgyNjcwMC8zMjg1NDA0NzQtMGM2MWJiZTYtNDFhYy00NzMyLThkMDktZDMxNzg2NDBmOTU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDE0MDcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhZGIwYjFiNzNkZDJkY2NkOTNhYmRjYjMyZDk1MzJmNDBjYzFiNTRkMTZjY2ZiMTg4YzIyMTc3ZTA0MTE1N2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z5SMGJzyADbovSpoxAfYF7xHcaqcnIeGYWYlnvZIQQM)

This updated commit should fix for both transactions and reviews when there are filters

2024-05-07 15:00 UTC, 0tuedon commented
> > When I'm on the review page, the Review text doesn't have a background color to show that I'm on that route like we have for the Transactions page. We should use the same background color when the review page is in focus ![image]


> This updated commit should fix for both transactions and reviews when there are filters

2024-05-07 15:01 UTC, 0tuedon commented
> > > When I'm on the review page, the Review text doesn't have a background color to show that I'm on that route like we have for the Transactions page. We should use the same background color when the review page is in focus ![image]
> 
 This updated commit should fix for both transactions and reviews when there are filters

2024-05-07 15:01 UTC, 0tuedon commented
> When I'm on the review page, the Review text doesn't have a background color to show that I'm on that route like we have for the Transactions page. We should use the same background color when the review page is in focus ![image]

> This updated commit should fix for both transactions and reviews when there are filters

2024-05-07 15:59 UTC, Extheoisah commented
Can you add some padding in between "Transactions" and "Reviews"? No need to create a new commit. You can just amend the recent commit to include this change

<img width="316" alt="Screenshot 2024-05-07 at 16 56 12" src="https://github.com/bitcointranscripts/transcription-review-front-end/assets/60826700/1327654e-5bc0-4a4d-81a0-370c5f52b4d0">

2024-05-07 17:53 UTC, 0tuedon commented
> Reset Review: Leverage the existing /api/reviews/{id}/reset API endpoint to allow admins to reset an active review in the same way that admins can archive a transcript in the /transcripts page.
Additional Table Fields Based on Status
For Active reviews: Include the remaining time before the review expires.
For Pending reviews: Include a link to the pull request URL (pr_url) and the submission date.
For Merged reviews: Display the fields available in Pending reviews, plus the date the review was merged and a link to the final transcript.
Note: For dates displayed in the table, including the exact time is essential. To maintain a clean layout, we can show only the date initially, with the full date and time details appearing in a tooltip upon hovering over the date.

When merging pls note that there will be an additional PR for this additional issues.

2024-05-07 20:32 UTC, Extheoisah approved these changes

2024-05-07 20:33 UTC, Extheoisah commented
merging now. @0tuedon Lets address the other issues in another pr

2024-05-07 20:38 UTC, merged

2024-05-09 12:27 UTC, kouloumos commented
Great work @0tuedon! A couple of issues while reviewing this post-merged:
1. The status column is not useful as it is, "queued" or "not queued" is not useful information. The status should be displayed as one of the actual status with which you can filter (active, merged, etc.). This way when you search for a specific user/transcript, you can see the actual status of the previous claims.
2. Filtering should reset the url. As it is, it creates issues when for example you go on the second page of the table and then apply a filtering.
3. Updated At is not useful as a column. Let's remove it on the next update.
4. The Transactions table has a count of Results on the top right corner, let's also add this here
5. "Expired" filter also displays merged reviews.